In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand()

0.11210314889064843

In [16]:
np.random.rand(4)

array([0.51417263, 0.0896724 , 0.67187168, 0.56793318])

In [17]:
np.random.rand(4,4)

array([[0.79554099, 0.92641294, 0.61614398, 0.06544101],
       [0.57222278, 0.12842448, 0.42045475, 0.22049488],
       [0.56063216, 0.60516378, 0.15359394, 0.14239846],
       [0.09261532, 0.82728077, 0.58963137, 0.06101615]])

In [18]:
np.random.randint(1,15)

2

In [19]:
np.random.randint(1,15,(10,10))

array([[14,  7, 12, 12,  4,  4,  7,  4, 14, 11],
       [12,  5,  3, 10,  8,  2, 10,  2,  2,  8],
       [ 6,  9, 14,  4, 10,  4,  2, 14,  6,  7],
       [13,  9, 10,  4,  4, 11,  8, 12, 14, 10],
       [11, 14,  5,  6, 14,  8,  1,  2,  6,  9],
       [ 1,  2,  1, 13, 14,  8,  1,  5,  4,  2],
       [ 4,  6,  2,  7,  4,  8,  1, 11,  1, 12],
       [10,  2, 13,  9,  4, 13, 12,  7,  9,  6],
       [ 9, 14, 14,  7,  3,  1,  9, 13,  8,  6],
       [11,  7,  4,  2, 14, 10,  5,  9,  8,  8]])