In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)

In [5]:
matrix = arr.reshape(2,5)
matrix

array([[14,  5,  5,  5,  4],
       [ 8, 16, 11,  8, 11]])

In [6]:
arr.max()

16

In [8]:
matrix.max(1)

array([14, 16])

In [9]:
matrix.max(0)

array([14, 16, 11,  8, 11])

In [11]:
arr

array([14,  5,  5,  5,  4,  8, 16, 11,  8, 11])

In [10]:
arr.argmax()

6

In [12]:
matrix.argmax(0)

array([0, 1, 1, 1, 1])

In [13]:
matrix.argmax(1)

array([0, 1])

In [14]:
arr.min()

4

In [15]:
matrix.min(0)

array([8, 5, 5, 5, 4])

In [16]:
arr.argmin()

4

In [18]:
matrix.argmin()

6

In [19]:
arr

array([14,  5,  5,  5,  4,  8, 16, 11,  8, 11])

In [20]:
arr.ptp()

12

In [21]:
matrix

array([[14,  5,  5,  5,  4],
       [ 8, 16, 11,  8, 11]])

In [23]:
matrix.ptp(0)

array([ 6, 11,  6,  3,  7])

In [26]:
np.percentile(arr,50)

8.0

In [27]:
arr.sort()
arr

array([ 4,  5,  5,  5,  8,  8, 11, 11, 14, 16])

In [28]:
np.median(arr)

8.0

In [29]:
np.std(arr)

3.950949253027682

In [30]:
np.var(arr)

15.61

In [31]:
np.mean(arr)

8.7

In [32]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
b = np.array([5,6])
b

array([5, 6])

In [35]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [39]:
b = np.expand_dims(b,axis=0)

In [40]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])