In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2 = arr.copy()

Operaciones

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr +2 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
1 / arr

/tmp/ipykernel_1974/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr / 0

/tmp/ipykernel_1974/3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
/tmp/ipykernel_1974/3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [11]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr / arr2

/tmp/ipykernel_1974/1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
matrix = arr.reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matrix2 = matrix.copy()

In [17]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [19]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])

In [20]:
arr + matrix

ValueError: operands could not be broadcast together with shapes (10,) (2,5) 

In [21]:
arr * matrix

ValueError: operands could not be broadcast together with shapes (10,) (2,5) 